steps:
  # Fetch secret from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['secrets', 'versions', 'access', 'latest', '--secret', 'firebase-service-account', '--out-file', '/workspace/secrets/firebase-service-account.json']

  # Build Angular app
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'Frontend'
    args: ['install']

  - name: 'node:18-alpine'
    dir: 'Frontend'
    args: ['npm','run', 'build']

  # Deploy Angular app to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'leave-management-frontend',
      '--source=Frontend',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

  # Deploy FastAPI backend to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'Backend/app'
    args: ['app', 'deploy', '--quiet']

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY